"""add_setup_wizard_fields

Revision ID: 2df615335c60
Revises: f4db2a8c08b1
Create Date: 2026-04-23 18:21:50.939585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df615335c60'
down_revision: Union[str, Sequence[str], None] = 'f4db2a8c08b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('setup_completed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('organizations', sa.Column('org_type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('invite_method', sa.String(length=50), nullable=False, server_default=sa.text("'email'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'invite_method')
    op.drop_column('organizations', 'org_type')
    op.drop_column('organizations', 'setup_completed')
    # ### end Alembic commands ###
