"""create_tasks_table

Revision ID: 465f07c33934
Revises: f663823375d8
Create Date: 2026-03-10 08:55:54.496662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '465f07c33934'
down_revision: Union[str, Sequence[str], None] = 'f663823375d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('logged_hours', sa.Float(), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        "idx_tasks_project_status",
        "tasks", ["project_id", "status"],
        postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(
        "idx_tasks_assignee",
        "tasks", ["assignee_id"],
        postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(
        "idx_tasks_due_date",
        "tasks", ["due_date"],
        postgresql_where=sa.text("completed_at IS NULL")
    )

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')

    op.drop_index("idx_tasks_project_status", table_name="tasks")
    op.drop_index("idx_tasks_assignee", table_name="tasks")
    op.drop_index("idx_tasks_due_date", table_name="tasks")
    op.drop_table('tasks')

    # ### end Alembic commands ###
