"""add_system_settings_remove_setup_completed

Revision ID: 784caf395b5d
Revises: 2df615335c60
Create Date: 2026-04-23 19:36:38.750799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784caf395b5d'
down_revision: Union[str, Sequence[str], None] = '2df615335c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('setup_completed', sa.Boolean(), nullable=False, server_default=sa.false()),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
            INSERT INTO system_settings (id, setup_completed)
            SELECT 1, COALESCE(MAX(setup_completed::int)::boolean, false)
            FROM organizations
        """)
    op.drop_column('organizations', 'setup_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('setup_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('system_settings')
    # ### end Alembic commands ###
