"""alter_task_comments_content_nullable

Revision ID: cbce7ae45324
Revises: dd147cc1d667
Create Date: 2026-04-07 10:30:44.701036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbce7ae45324'
down_revision: Union[str, Sequence[str], None] = 'dd147cc1d667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_comments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_comments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
