"""add_stack_to_projects

Revision ID: dd147cc1d667
Revises: 07307cabdbd0
Create Date: 2026-03-30 19:47:11.776825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd147cc1d667'
down_revision: Union[str, Sequence[str], None] = '07307cabdbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_project'), table_name='activity_logs')
    op.drop_index(op.f('idx_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.add_column('projects', sa.Column('stack', sa.ARRAY(sa.String()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'stack')
    op.create_index(op.f('idx_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_activity_project'), 'activity_logs', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
