"""BE-11 invitation system

Revision ID: e91f35e203b3
Revises: 784caf395b5d
Create Date: 2026-04-26 18:19:50.749643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91f35e203b3'
down_revision: Union[str, Sequence[str], None] = '784caf395b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_allowlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('auto_role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'domain', name='uq_org_domain')
    )
    op.create_table('invite_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('invite_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'invited_user_id', 'status', name='uq_invitation_pending')
    )

    op.create_index("ix_invitations_org_status", "invitations", ["organization_id", "status"])
    op.create_index("ix_invitations_user_status", "invitations", ["invited_user_id", "status"])
    op.create_index("ix_invitations_project_status", "invitations", ["project_id", "status"])
    op.create_index("ix_invite_links_token", "invite_links", ["token"])
    op.create_index("ix_invite_links_org_active", "invite_links", ["organization_id", "is_active"])
    op.create_index("ix_domain_allowlist_domain", "domain_allowlist", ["domain"])

    op.add_column('organization_members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'deleted_at')
    op.drop_column('organization_members', 'deleted_at')

    op.drop_index("ix_domain_allowlist_domain", table_name="domain_allowlist")
    op.drop_index("ix_invite_links_org_active", table_name="invite_links")
    op.drop_index("ix_invite_links_token", table_name="invite_links")
    op.drop_index("ix_invitations_project_status", table_name="invitations")
    op.drop_index("ix_invitations_user_status", table_name="invitations")
    op.drop_index("ix_invitations_org_status", table_name="invitations")

    op.drop_table('invitations')
    op.drop_table('invite_links')
    op.drop_table('domain_allowlist')
    # ### end Alembic commands ###
