"""update_attachments_table

Revision ID: f4db2a8c08b1
Revises: cbce7ae45324
Create Date: 2026-04-09 04:24:43.992004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4db2a8c08b1'
down_revision: Union[str, Sequence[str], None] = 'cbce7ae45324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('project_id', sa.UUID(), nullable=False))
    op.add_column('attachments', sa.Column('storage_path', sa.Text(), nullable=False))
    op.add_column('attachments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('attachments', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'attachments', 'projects', ['project_id'], ['id'])
    op.drop_column('attachments', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.alter_column('attachments', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('attachments', 'deleted_at')
    op.drop_column('attachments', 'storage_path')
    op.drop_column('attachments', 'project_id')
    # ### end Alembic commands ###
